import { v } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import { query } from "./_generated/server";
import { requireProjectOwner } from "./lib/auth";
function normalizeWords(s:string):Set<string>{return new Set(s.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean));}
function hintMatchesLineItem(itemHint:string,lineItemName:string):boolean{const nameWords=normalizeWords(lineItemName);if(nameWords.size===0)return false;const hintWords=normalizeWords(itemHint);let overlap=0;for(const w of nameWords)if(hintWords.has(w))overlap++;return overlap/nameWords.size>=.5;}
const cellFields={supplierId:v.id("suppliers"),unitPrice:v.number(),total:v.number(),matchConfidence:v.number(),previousUnitPrice:v.optional(v.number())};
const rowFields={lineItemId:v.id("lineItems"),name:v.string(),spec:v.string(),quantity:v.number(),unit:v.string(),bestSupplierId:v.optional(v.id("suppliers")),bestPrice:v.optional(v.number()),worstPrice:v.optional(v.number()),publishedPrice:v.optional(v.number()),cells:v.array(v.object(cellFields))};
const columnFields={supplierId:v.id("suppliers"),supplierName:v.string(),quoteVersion:v.number(),deliveryCost:v.optional(v.number()),basketTotal:v.number(),coveragePercent:v.number(),missingLineItemIds:v.array(v.id("lineItems"))};
export const comparisonMatrix=query({args:{projectId:v.id("projects")},returns:v.object({rows:v.array(v.object(rowFields)),columns:v.array(v.object(columnFields)),bestFullCoverageSupplierId:v.optional(v.id("suppliers")),bestFullCoverageBasketTotal:v.optional(v.number()),bestSplitBasketTotal:v.optional(v.number()),splitSavings:v.optional(v.number())}),handler:async(ctx,args)=>{await requireProjectOwner(ctx,args.projectId);const lineItems=await ctx.db.query("lineItems").withIndex("by_project",q=>q.eq("projectId",args.projectId)).take(1000);const sortedLineItems=[...lineItems].sort((a,b)=>a.sortOrder-b.sortOrder);const allQuotes=await ctx.db.query("quotes").withIndex("by_project",q=>q.eq("projectId",args.projectId)).take(1000);const latestQuoteBySupplier=new Map<string,Doc<"quotes">>();for(const quote of allQuotes){const key=quote.supplierId as string;const current=latestQuoteBySupplier.get(key);if(!current||quote.version>current.version)latestQuoteBySupplier.set(key,quote);}if(latestQuoteBySupplier.size===0)return{rows:[],columns:[]};const latestQuoteIds=new Set([...latestQuoteBySupplier.values()].map(q=>q._id as string));const quotesBySupplier=new Map<string,Doc<"quotes">[]>();for(const quote of allQuotes){const key=quote.supplierId as string;if(!quotesBySupplier.has(key))quotesBySupplier.set(key,[]);quotesBySupplier.get(key)!.push(quote);}const secondLatestQuoteBySupplier=new Map<string,Doc<"quotes">>();for(const[key,supplierQuotes]of quotesBySupplier){const sorted=[...supplierQuotes].sort((a,b)=>b.version-a.version);if(sorted.length>1)secondLatestQuoteBySupplier.set(key,sorted[1]);}const secondLatestQuoteIds=new Set([...secondLatestQuoteBySupplier.values()].map(q=>q._id as string));const allQuoteLines=await ctx.db.query("quoteLines").withIndex("by_project",q=>q.eq("projectId",args.projectId)).take(5000);const cellsBySupplier=new Map<string,Map<string,Doc<"quoteLines">>>();const prevCellsBySupplier=new Map<string,Map<string,Doc<"quoteLines">>>();for(const line of allQuoteLines){if(!line.lineItemId)continue;const supplierKey=line.supplierId as string;if(latestQuoteIds.has(line.quoteId as string)){if(!cellsBySupplier.has(supplierKey))cellsBySupplier.set(supplierKey,new Map());cellsBySupplier.get(supplierKey)!.set(line.lineItemId as string,line);}else if(secondLatestQuoteIds.has(line.quoteId as string)){if(!prevCellsBySupplier.has(supplierKey))prevCellsBySupplier.set(supplierKey,new Map());prevCellsBySupplier.get(supplierKey)!.set(line.lineItemId as string,line);}}
const suppliers=await ctx.db.query("suppliers").withIndex("by_project",q=>q.eq("projectId",args.projectId)).take(500);const supplierById=new Map(suppliers.map(s=>[s._id as string,s]));const columnSupplierIds=[...latestQuoteBySupplier.keys()];const rows=sortedLineItems.map(item=>{const cells=columnSupplierIds.map(supplierKey=>{const line=cellsBySupplier.get(supplierKey)?.get(item._id as string);if(!line)return null;const prevLine=prevCellsBySupplier.get(supplierKey)?.get(item._id as string);return{supplierId:line.supplierId,unitPrice:line.unitPrice,total:line.unitPrice*item.quantity,matchConfidence:line.matchConfidence,previousUnitPrice:prevLine?.unitPrice};}).filter((c):c is NonNullable<typeof c>=>c!==null);let bestSupplierId:Id<"suppliers">|undefined;let bestPrice:number|undefined;let worstPrice:number|undefined;for(const cell of cells){if(bestPrice===undefined||cell.unitPrice<bestPrice){bestPrice=cell.unitPrice;bestSupplierId=cell.supplierId;}if(worstPrice===undefined||cell.unitPrice>worstPrice)worstPrice=cell.unitPrice;}let publishedPrice:number|undefined;for(const supplier of suppliers)for(const listPrice of supplier.listPrices??[])if(hintMatchesLineItem(listPrice.itemHint,item.name)&&(publishedPrice===undefined||listPrice.price<publishedPrice))publishedPrice=listPrice.price;return{lineItemId:item._id,name:item.name,spec:item.spec,quantity:item.quantity,unit:item.unit,bestSupplierId,bestPrice,worstPrice,publishedPrice,cells};});
const columns=columnSupplierIds.map(supplierKey=>{const supplier=supplierById.get(supplierKey);const quote=latestQuoteBySupplier.get(supplierKey)!;const supplierCells=cellsBySupplier.get(supplierKey)??new Map();let itemsTotal=0;const missingLineItemIds:Id<"lineItems">[]=[];for(const item of sortedLineItems){const line=supplierCells.get(item._id as string);if(line)itemsTotal+=line.unitPrice*item.quantity;else missingLineItemIds.push(item._id);}const basketTotal=itemsTotal+(quote.deliveryCost??0);const coveragePercent=sortedLineItems.length>0?Math.round(((sortedLineItems.length-missingLineItemIds.length)/sortedLineItems.length)*100):0;return{supplierId:quote.supplierId,supplierName:supplier?.name??"Unknown supplier",quoteVersion:quote.version,deliveryCost:quote.deliveryCost,basketTotal,coveragePercent,missingLineItemIds};});
let bestFullCoverageSupplierId:Id<"suppliers">|undefined;let bestFullCoverageBasketTotal:number|undefined;for(const col of columns)if(col.coveragePercent===100&&(bestFullCoverageBasketTotal===undefined||col.basketTotal<bestFullCoverageBasketTotal)){bestFullCoverageBasketTotal=col.basketTotal;bestFullCoverageSupplierId=col.supplierId;}
let bestSplitBasketTotal:number|undefined;if(rows.some(r=>r.bestPrice!==undefined)){let itemsTotal=0;const suppliersUsed=new Set<string>();let coversEveryRow=true;for(const row of rows){if(row.bestPrice===undefined||row.bestSupplierId===undefined){coversEveryRow=false;continue;}itemsTotal+=row.bestPrice*row.quantity;suppliersUsed.add(row.bestSupplierId as string);}if(coversEveryRow){let deliveryTotal=0;for(const supplierKey of suppliersUsed)deliveryTotal+=latestQuoteBySupplier.get(supplierKey)?.deliveryCost??0;bestSplitBasketTotal=itemsTotal+deliveryTotal;}}const splitSavings=bestFullCoverageBasketTotal!==undefined&&bestSplitBasketTotal!==undefined?bestFullCoverageBasketTotal-bestSplitBasketTotal:undefined;return{rows,columns,bestFullCoverageSupplierId,bestFullCoverageBasketTotal,bestSplitBasketTotal,splitSavings};}});
