import { internalMutation, mutation } from "./_generated/server";
import { v } from "convex/values";
import type { MutationCtx } from "./_generated/server";
import type { Id } from "./_generated/dataModel";
import { requireProjectOwner } from "./lib/auth";
import { replyInThread } from "./lib/threadReply";
const PRICE_TOLERANCE=.01;function priceExistsInQuoteLines(price:number,real:number[]){return real.some(p=>Math.abs(p-price)<PRICE_TOLERANCE)}function extractNumericTokens(text:string){const m=text.match(/(?<![A-Za-z0-9])(?:₦|NGN|USD|\$|EUR|€|GBP|£)?\s*\d[\d,]*(?:\.\d+)?/gi)??[];return m.map(x=>Number(x.replace(/[^\d.]/g,"").replace(/,/g,""))).filter(Number.isFinite)}async function validate(ctx:MutationCtx,projectId:Id<"projects">,text:string,cited:number[]|undefined){const lines=await ctx.db.query("quoteLines").withIndex("by_project",q=>q.eq("projectId",projectId)).take(5000);const real=lines.map(l=>l.unitPrice);const body=extractNumericTokens(text);const invalid=body.filter(p=>!priceExistsInQuoteLines(p,real));if(invalid.length)return`Blocked: this draft contains a price (${invalid.join(", ")}) that doesn't match any stored quote.`;if(cited){const bad=cited.filter(p=>!priceExistsInQuoteLines(p,real));if(bad.length)return`Blocked: this draft cites a price (${bad.join(", ")}) that doesn't match any stored quote.`;const missing=cited.filter(p=>!body.some(x=>Math.abs(x-p)<PRICE_TOLERANCE));if(missing.length)return`Blocked: the draft's cited price (${missing.join(", ")}) is not present in the final message.`;}return null}
export const insertNegotiationDraft=internalMutation({args:{projectId:v.id("projects"),supplierId:v.id("suppliers"),subject:v.string(),body:v.string(),citedPrices:v.array(v.number())},returns:v.union(v.object({ok:v.literal(true),draftId:v.id("drafts")}),v.object({ok:v.literal(false),reason:v.string()})),handler:async(ctx,args)=>{const lines=await ctx.db.query("quoteLines").withIndex("by_project",q=>q.eq("projectId",args.projectId)).take(5000);const real=lines.map(l=>l.unitPrice);const bad=args.citedPrices.filter(p=>!priceExistsInQuoteLines(p,real));if(bad.length)return{ok:false as const,reason:`Blocked: this draft cites a price (${bad.join(", ")}) that doesn't match any stored quote.`};const draftId=await ctx.db.insert("drafts",{projectId:args.projectId,supplierId:args.supplierId,kind:"counter",subject:args.subject,body:args.body,status:"pending",citedPrices:args.citedPrices});return{ok:true as const,draftId};}});
export const sendNegotiationDraft=mutation({args:{draftId:v.id("drafts")},returns:v.object({ok:v.boolean(),blockedReason:v.optional(v.string())}),handler:async(ctx,args)=>{const d=await ctx.db.get(args.draftId);if(!d)throw new Error("Draft not found");await requireProjectOwner(ctx,d.projectId);if(d.kind!=="counter")throw new Error("Not a negotiation draft");if(d.status!=="pending")throw new Error("Draft is not pending");const err=await validate(ctx,d.projectId,d.subject+"\n"+d.body,d.citedPrices);if(err)return{ok:false,blockedReason:err};await ctx.db.patch(args.draftId,{status:"approved"});const result=await replyInThread(ctx,{projectId:d.projectId,supplierId:d.supplierId,blockedEventType:"negotiation_send_blocked",body:d.body});if(!result.ok)return result;await ctx.db.patch(args.draftId,{status:"sent"});await ctx.db.insert("events",{projectId:d.projectId,type:"negotiation_sent",payload:{supplierId:d.supplierId},createdAt:Date.now()});return{ok:true};}});
