import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  ...authTables,
  projects: defineTable({ ownerId: v.id("users"), name: v.string(), jobDescription: v.string(), location: v.string(), currency: v.string(), status: v.union(v.literal("draft"), v.literal("boq_ready"), v.literal("sourcing"), v.literal("rfq_sent"), v.literal("comparing"), v.literal("awarded"), v.literal("cancelled")), inboxId: v.optional(v.string()), inboxAddress: v.optional(v.string()), attachmentIds: v.optional(v.array(v.id("_storage"))), autoApproveFollowUps: v.optional(v.boolean()), createdAt: v.number(), awardId: v.optional(v.id("awards")), awardedAt: v.optional(v.number()) }).index("by_owner", ["ownerId"]).index("by_inbox_id", ["inboxId"]),
  lineItems: defineTable({ projectId: v.id("projects"), name: v.string(), spec: v.string(), quantity: v.number(), unit: v.string(), category: v.string(), sortOrder: v.number() }).index("by_project", ["projectId"]),
  suppliers: defineTable({ projectId: v.id("projects"), name: v.string(), website: v.optional(v.string()), email: v.optional(v.string()), source: v.union(v.literal("firecrawl"), v.literal("manual"), v.literal("demo")), categories: v.array(v.string()), listPrices: v.optional(v.array(v.object({ itemHint: v.string(), price: v.number(), unit: v.string() }))), status: v.union(v.literal("candidate"), v.literal("selected"), v.literal("rfq_sent"), v.literal("replied"), v.literal("declined"), v.literal("silent")) }).index("by_project", ["projectId"]),
  threads: defineTable({ projectId: v.id("projects"), supplierId: v.id("suppliers"), providerThreadId: v.string(), lastMessageAt: v.number(), followUpsSent: v.number(), pendingFollowUpScheduledId: v.optional(v.id("_scheduled_functions")) }).index("by_project", ["projectId"]).index("by_supplier", ["supplierId"]).index("by_provider_thread_id", ["providerThreadId"]),
  messages: defineTable({ threadId: v.optional(v.id("threads")), projectId: v.id("projects"), supplierId: v.optional(v.id("suppliers")), providerMessageId: v.string(), direction: v.union(v.literal("out"), v.literal("in")), subject: v.string(), bodyText: v.string(), attachmentIds: v.array(v.id("_storage")), receivedAt: v.number(), processed: v.boolean() }).index("by_project", ["projectId"]).index("by_thread", ["threadId"]).index("by_supplier", ["supplierId"]).index("by_provider_message_id", ["providerMessageId"]),
  quotes: defineTable({ projectId: v.id("projects"), supplierId: v.id("suppliers"), messageId: v.id("messages"), validUntil: v.optional(v.number()), leadTimeDays: v.optional(v.number()), deliveryCost: v.optional(v.number()), currency: v.string(), confidence: v.number(), notes: v.optional(v.string()), version: v.number() }).index("by_project", ["projectId"]).index("by_supplier", ["supplierId"]).index("by_message", ["messageId"]).index("by_valid_until", ["validUntil"]),
  quoteLines: defineTable({ quoteId: v.id("quotes"), projectId: v.id("projects"), supplierId: v.id("suppliers"), lineItemId: v.optional(v.id("lineItems")), rawDescription: v.string(), unitPrice: v.number(), unit: v.string(), quantity: v.number(), total: v.number(), matchConfidence: v.number() }).index("by_project", ["projectId"]).index("by_quote", ["quoteId"]).index("by_supplier", ["supplierId"]).index("by_project_line", ["projectId", "lineItemId"]),
  drafts: defineTable({ projectId: v.id("projects"), supplierId: v.id("suppliers"), kind: v.union(v.literal("rfq"), v.literal("follow_up"), v.literal("counter"), v.literal("award"), v.literal("decline"), v.literal("reply")), subject: v.string(), body: v.string(), status: v.union(v.literal("pending"), v.literal("approved"), v.literal("sent"), v.literal("discarded")), citedPrices: v.optional(v.array(v.number())), rfqLineItemIds: v.optional(v.array(v.id("lineItems"))), attachmentId: v.optional(v.id("_storage")) }).index("by_project", ["projectId"]).index("by_supplier", ["supplierId"]),
  awards: defineTable({ projectId: v.id("projects"), mode: v.union(v.literal("single"), v.literal("split")), deliveryAddress: v.string(), deliveryDate: v.string(), totalSpend: v.number(), highestQuote: v.number(), publishedListTotal: v.number(), awardedAt: v.number() }).index("by_project", ["projectId"]),
  awardLines: defineTable({ awardId: v.id("awards"), projectId: v.id("projects"), supplierId: v.id("suppliers"), lineItemId: v.id("lineItems"), quantity: v.number(), unit: v.string(), unitPrice: v.number(), total: v.number() }).index("by_award", ["awardId"]),
  events: defineTable({ projectId: v.id("projects"), type: v.union(v.literal("project_created"), v.literal("inbox_provisioned"), v.literal("message_received"), v.literal("message_unmatched"), v.literal("message_classified"), v.literal("project_awarded"), v.literal("award_send_blocked"), v.literal("po_sent"), v.literal("decline_sent"), v.literal("award_draft_created"), v.literal("boq_ready"), v.literal("rfq_sent"), v.literal("quote_received"), v.literal("project_cancelled"), v.literal("follow_up_sent"), v.literal("supplier_selected"), v.literal("draft_created"), v.literal("boq_generated"), v.literal("rfq_send_blocked"), v.literal("quote_expiring"), v.literal("negotiation_send_blocked"), v.literal("negotiation_sent"), v.literal("award_validation_failed")), payload: v.any(), createdAt: v.number() }).index("by_project", ["projectId"]),
});
