import { useQuery } from 'convex/react'
import { Link } from 'react-router-dom'
import { api } from '../../convex/_generated/api'
import { PageSkeleton, StatusPill } from '../components/ui'

function directionLabel(direction: 'up' | 'down' | 'stable') { if (direction === 'up') return '↑ rising'; if (direction === 'down') return '↓ falling'; return '→ stable' }

export function InsightsPage() {
  const insights = useQuery(api.insights.workspaceInsights)
  if (insights === undefined) return <PageSkeleton />
  return <div className="min-h-screen bg-[#070908] text-neutral-100">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#070908]/90 px-4 backdrop-blur-xl sm:px-6"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between"><Link to="/" className="flex items-center gap-2 text-sm font-bold uppercase tracking-[.16em]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-amber-400 text-black">B</span> BidWire</Link><Link to="/" className="text-xs text-neutral-500 hover:text-white">← Projects</Link></div></header>
    <main className="mx-auto max-w-[1440px] space-y-8 px-4 py-8 sm:px-6 sm:py-10">
      <div><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-400">Then · procurement intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em] sm:text-4xl">Workspace insights</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-neutral-500">Turn procurement history BidWire has actually collected into spend visibility, observed price movement, lead-time signals and an action queue. No fabricated market data or forecasts are shown.</p></div>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Projects", insights.summary.projects], ["Awarded", insights.summary.awardedProjects], ["Active", insights.summary.activeProjects], ["Quotes", insights.summary.quotes], ["Replied suppliers", insights.summary.suppliersReplied], ["Contacted suppliers", insights.summary.suppliersContacted]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs text-neutral-600">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</section>
      <section className="rounded-2xl border border-amber-500/15 bg-amber-500/[.035] p-5"><div><p className="text-xs uppercase tracking-[.16em] text-amber-400">Procurement autopilot</p><h2 className="mt-1 text-lg font-semibold">Current action queue</h2><p className="mt-1 text-xs text-neutral-500">Visibility into pending work and scheduled follow-ups. Existing project controls still govern outbound communication.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Pending follow-ups", insights.autopilot.pendingFollowUps], ["Silent suppliers", insights.autopilot.silentSuppliers], ["Quotes expiring · 7d", insights.autopilot.expiringQuotes], ["Projects awaiting compare", insights.autopilot.projectsAwaitingComparison], ["Scheduled follow-up threads", insights.autopilot.scheduledThreads]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-[11px] text-neutral-600">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div></section>
      <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><p className="text-xs uppercase tracking-[.16em] text-neutral-600">Spend analytics</p><h2 className="mt-1 text-lg font-semibold">Awarded spend by currency</h2><div className="mt-4 space-y-2">{insights.spendByCurrency.length === 0 ? <p className="text-sm text-neutral-600">No awarded projects yet.</p> : insights.spendByCurrency.map(row => <div key={row.currency} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/10 px-4 py-3"><div><p className="text-sm font-medium">{row.currency}</p><p className="text-xs text-neutral-600">{row.awards} award{row.awards === 1 ? '' : 's'} · average {row.averageAward.toLocaleString()}</p></div><p className="text-lg font-semibold text-emerald-300">{row.totalSpend.toLocaleString()}</p></div>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><p className="text-xs uppercase tracking-[.16em] text-neutral-600">Project history</p><h2 className="mt-1 text-lg font-semibold">Largest awarded projects</h2><div className="mt-4 space-y-2">{insights.spendByProject.length === 0 ? <p className="text-sm text-neutral-600">No awarded project spend recorded yet.</p> : insights.spendByProject.map(row => <Link key={row.projectId} to={`/p/${row.projectId}`} className="flex items-center justify-between rounded-xl border border-white/10 bg-black/10 px-4 py-3 hover:border-white/20"><div><p className="text-sm font-medium">{row.projectName}</p><p className="mt-1 text-xs text-neutral-600">{row.currency} · {row.status}</p></div><p className="text-sm font-semibold">{row.spend.toLocaleString()}</p></Link>)}</div></div></section>
      <section className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><p className="text-xs uppercase tracking-[.16em] text-neutral-600">Historical price intelligence</p><h2 className="mt-1 text-lg font-semibold">Observed quote movement</h2><p className="mt-1 text-xs text-neutral-600">Only items with at least two observed quote prices are shown. Direction is historical movement, not a market forecast.</p>{insights.priceSignals.length === 0 ? <div className="mt-5 rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-neutral-600">Collect more supplier quotes across projects to unlock historical item signals.</div> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead><tr className="border-b border-white/10 text-left text-xs text-neutral-600"><th className="px-3 py-3">Item</th><th className="px-3 py-3">Observations</th><th className="px-3 py-3">Average</th><th className="px-3 py-3">Range</th><th className="px-3 py-3">Latest</th><th className="px-3 py-3">Signal</th></tr></thead><tbody>{insights.priceSignals.map(row => <tr key={`${row.itemName}-${row.unit}-${row.currency}`} className="border-b border-white/[.05]"><td className="px-3 py-3"><p className="font-medium">{row.itemName}</p><p className="text-xs text-neutral-600">per {row.unit} · {row.currency}</p></td><td className="px-3 py-3 text-neutral-400">{row.observations}</td><td className="px-3 py-3">{row.averageUnitPrice.toLocaleString()}</td><td className="px-3 py-3 text-neutral-500">{row.lowestUnitPrice.toLocaleString()}–{row.highestUnitPrice.toLocaleString()}</td><td className="px-3 py-3 font-medium">{row.latestUnitPrice.toLocaleString()}</td><td className={`px-3 py-3 ${row.direction === 'up' ? 'text-amber-300' : row.direction === 'down' ? 'text-emerald-300' : 'text-neutral-500'}`}>{directionLabel(row.direction)}</td></tr>)}</tbody></table></div>}</section>
      <section className="rounded-2xl border border-white/10 bg-white/[.02] p-5"><p className="text-xs uppercase tracking-[.16em] text-neutral-600">Lead-time intelligence</p><h2 className="mt-1 text-lg font-semibold">Observed supplier lead-time movement</h2><p className="mt-1 text-xs text-neutral-600">A supplier appears only when BidWire has at least two recorded lead-time observations.</p>{insights.leadTimeSignals.length === 0 ? <div className="mt-5 rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-neutral-600">More historical quotes are needed before a lead-time trend can be shown.</div> : <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{insights.leadTimeSignals.map(row => <div key={row.supplierName} className="rounded-xl border border-white/10 bg-black/10 p-4"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium">{row.supplierName}</p><StatusPill tone={row.direction === 'down' ? 'green' : row.direction === 'up' ? 'amber' : 'neutral'}>{directionLabel(row.direction)}</StatusPill></div><p className="mt-4 text-2xl font-semibold">{row.latestDays} <span className="text-sm font-normal text-neutral-600">days</span></p><p className="mt-1 text-xs text-neutral-600">{row.observations} observations{row.previousDays !== undefined ? ` · previous ${row.previousDays} days` : ''}</p></div>)}</div>}</section>
      <div className="rounded-xl border border-white/10 bg-white/[.02] p-4 text-xs leading-5 text-neutral-600">BidWire labels these as observed signals. It does not invent market prices, supplier performance, or future outcomes when the workspace does not contain enough evidence.</div>
    </main>
  </div>
}
