import { useQuery } from 'convex/react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { api } from '../../convex/_generated/api'
import type { Doc, Id } from '../../convex/_generated/dataModel'
import { NegotiationDrafts, NegotiateButton } from './NegotiationDrafts'
import { AwardPanel } from './AwardPanel'
import { ProcurementBriefModal } from './ProcurementBrief'
import { Skeleton, EmptyState, StatusPill } from './ui'

type AwardMode='single'|'split'

function useFlashingCells(map:Map<string,number>):Set<string>{const previous=useRef<Map<string,number>>(new Map());const[flashing,setFlashing]=useState<Set<string>>(new Set());useEffect(()=>{const changed=new Set<string>();for(const[key,price]of map){const prev=previous.current.get(key);if(prev!==undefined&&prev!==price)changed.add(key)}previous.current=new Map(map);if(changed.size){setFlashing(changed);const t=setTimeout(()=>setFlashing(new Set()),1500);return()=>clearTimeout(t)}},[map]);return flashing}

export function CompareTab({project}:{project:Doc<'projects'>}){
 const matrix=useQuery(api.comparison.comparisonMatrix,{projectId:project._id});const award=useQuery(api.awards.getAward,{projectId:project._id});const awardLines=useQuery(api.awards.getAwardLines,award?{awardId:award.awardId}:"skip");const[awardMode,setAwardMode]=useState<AwardMode>('single');const[negotiationDraftId,setNegotiationDraftId]=useState<Id<'drafts'>|null>(null);const[briefOpen,setBriefOpen]=useState(false);const cellKeyToPrice=new Map<string,number>();for(const row of matrix?.rows??[])for(const cell of row.cells)cellKeyToPrice.set(`${row.lineItemId}:${cell.supplierId}`,cell.unitPrice);const flashing=useFlashingCells(cellKeyToPrice);
 const revisions=useMemo(()=>matrix?.rows.flatMap(row=>row.cells.filter(cell=>cell.previousUnitPrice!==undefined&&cell.previousUnitPrice!==cell.unitPrice).map(cell=>({row,cell})))??[],[matrix])
 if(matrix===undefined)return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Skeleton className="h-24"/><Skeleton className="h-24"/><Skeleton className="h-24"/></div><Skeleton className="h-12 w-56"/><Skeleton className="h-96 w-full"/></div>
 if(matrix.columns.length===0)return <EmptyState icon="↔" title="Waiting for supplier quotes" description="Once supplier replies are received and processed, their prices will appear here in real time."/>
 const sortedColumns=[...matrix.columns].sort((a,b)=>a.basketTotal-b.basketTotal);const cheapestBasket=sortedColumns[0];const splitSupplierIds=awardMode==='split'?new Set(matrix.rows.map(r=>r.bestSupplierId).filter((id):id is Id<'suppliers'>=>!!id)):null;
 return <div className="space-y-5">
  {award && <div className="rounded-2xl border border-emerald-500/20 bg-emerald-950/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.16em] text-emerald-400">Award completed</p><p className="mt-1 text-sm text-neutral-400">This comparison is now a record of the awarded decision.</p></div><div className="text-right"><p className="text-xl font-semibold text-emerald-300">{award.totalSpend.toLocaleString()} {project.currency}</p><p className="text-xs text-neutral-600">total awarded spend</p></div></div></div>}
  <div className="flex flex-col gap-3 xl:flex-row xl:items-stretch"><div className="flex-1 rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs uppercase tracking-[.16em] text-neutral-600">Decision view</p><div className="mt-2 flex flex-wrap items-end gap-x-8 gap-y-2"><div><p className="text-2xl font-semibold tracking-tight">{matrix.bestFullCoverageBasketTotal?.toLocaleString()??'—'} <span className="text-sm font-normal text-neutral-600">{project.currency}</span></p><p className="text-xs text-neutral-500">best full-coverage basket</p></div>{matrix.bestSplitBasketTotal!==undefined&&<div><p className="text-xl font-semibold">{matrix.bestSplitBasketTotal.toLocaleString()} <span className="text-sm font-normal text-neutral-600">{project.currency}</span></p><p className="text-xs text-neutral-500">best split basket</p></div>}</div></div><div className="flex flex-wrap gap-2 rounded-2xl border border-white/10 bg-white/[.025] p-1"><button onClick={()=>setAwardMode('single')} className={`rounded-xl px-4 py-2 text-sm font-medium ${awardMode==='single'?'bg-white text-black':'text-neutral-500 hover:text-white'}`}>Single supplier</button><button onClick={()=>setAwardMode('split')} className={`rounded-xl px-4 py-2 text-sm font-medium ${awardMode==='split'?'bg-white text-black':'text-neutral-500 hover:text-white'}`}>Cheapest split</button><button onClick={()=>setBriefOpen(true)} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-medium text-neutral-300 hover:border-white/20 hover:text-white">Procurement brief</button></div></div>
  {revisions.length>0&&<div className="rounded-2xl border border-emerald-900/40 bg-emerald-950/10 p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-emerald-400">Quote changes</p><p className="mt-1 text-sm text-neutral-400">BidWire detected {revisions.length} revised quote line{revisions.length===1?'':'s'} since earlier supplier responses.</p></div><button onClick={()=>setBriefOpen(true)} className="text-xs text-neutral-400 hover:text-white">Review brief →</button></div><div className="mt-3 flex flex-wrap gap-2">{revisions.slice(0,6).map(({row,cell})=>{const pct=cell.previousUnitPrice>0?Math.round(((cell.previousUnitPrice-cell.unitPrice)/cell.previousUnitPrice)*100):0;return <span key={`${row.lineItemId}-${cell.supplierId}`} className="rounded-full border border-white/10 bg-black/20 px-3 py-1.5 text-xs text-neutral-300">{row.name}: {pct>0?'↓':'↑'} {Math.abs(pct)}%</span>})}</div></div>}
  <div className="flex flex-wrap gap-2">{matrix.rows.map(row=>{if(row.bestPrice===undefined||row.worstPrice===undefined||row.worstPrice===row.bestPrice)return null;const pct=Math.round(((row.worstPrice-row.bestPrice)/row.worstPrice)*100);if(pct<10)return null;const best=matrix.columns.find(c=>c.supplierId===row.bestSupplierId);return <div key={row.lineItemId} className="rounded-full border border-emerald-500/20 bg-emerald-500/[.06] px-3 py-1.5 text-xs text-emerald-300">{best?.supplierName} is {pct}% cheaper on {row.name}</div>})}</div>
  <div className="overflow-x-auto rounded-2xl border border-white/10 bg-[#0b0e0c] shadow-2xl shadow-black/10"><table className="w-full min-w-[820px] text-sm"><thead><tr className="border-b border-white/10 text-left text-neutral-600"><th className="sticky left-0 z-10 bg-[#0b0e0c] px-4 py-3 font-medium">Item</th><th className="px-4 py-3 font-medium">Published</th>{sortedColumns.map(col=><th key={col.supplierId} className="min-w-[150px] px-4 py-3 font-medium"><div className="flex items-center gap-2 text-neutral-300">{col.supplierName}{col.supplierId===cheapestBasket?.supplierId&&<StatusPill tone="green">Best basket</StatusPill>}</div><div className="mt-1 text-xs text-neutral-700">{col.coveragePercent}% coverage · {col.basketTotal.toLocaleString()}</div></th>)}</tr></thead><tbody>{matrix.rows.map(row=><tr key={row.lineItemId} className="border-b border-white/[.055] last:border-0"><td className="sticky left-0 z-10 bg-[#0b0e0c] px-4 py-3"><p className="font-medium text-neutral-200">{row.name}</p><p className="mt-0.5 text-xs text-neutral-600">{row.quantity} {row.unit}</p></td><td className="px-4 py-3 text-xs text-neutral-600">{row.publishedPrice!==undefined?row.publishedPrice.toLocaleString():'—'}</td>{sortedColumns.map(col=>{const cell=row.cells.find(c=>c.supplierId===col.supplierId);const key=`${row.lineItemId}:${col.supplierId}`;const isBest=!!cell&&row.bestSupplierId===col.supplierId;const isSplit=splitSupplierIds!==null&&!!cell&&row.bestSupplierId===col.supplierId&&splitSupplierIds.has(col.supplierId);const rev=cell?.previousUnitPrice!==undefined&&cell.previousUnitPrice>0&&cell.unitPrice<cell.previousUnitPrice?Math.round(((cell.previousUnitPrice-cell.unitPrice)/cell.previousUnitPrice)*100):0;return <td key={col.supplierId} className={`px-4 py-3 transition-colors duration-1000 ${flashing.has(key)?'bg-amber-500/20':''} ${(awardMode==='single'&&isBest)||(awardMode==='split'&&isSplit)?'bg-emerald-950/30 text-emerald-300':'text-neutral-400'}`}>{cell?<><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{cell.unitPrice.toLocaleString()}</span>{rev>0&&<span className="text-[10px] font-semibold text-emerald-400">revised ↓ {rev}%</span>}</div><div className="mt-2 flex items-center gap-2">{cell.matchConfidence<.7&&<span className="text-amber-500" title="Needs review">⚠</span>}<NegotiateButton projectId={project._id} supplierId={col.supplierId} lineItemId={row.lineItemId} disabled={project.status==='awarded'} onDraftReady={setNegotiationDraftId}/></div></>:<span className="text-neutral-800">Not quoted</span>}</td>})}</tr>)}</tbody></table></div>
  <NegotiationDrafts project={project} openDraftId={negotiationDraftId} onClose={()=>setNegotiationDraftId(null)}/><AwardPanel project={project}/>{briefOpen&&<ProcurementBriefModal project={project} matrix={matrix} award={award} awardLines={awardLines} onClose={()=>setBriefOpen(false)}/>} 
 </div>
}
