import { useAction, useMutation, useQuery } from 'convex/react'
import { useState } from 'react'
import { api } from '../../convex/_generated/api'
import type { Doc, Id } from '../../convex/_generated/dataModel'
import { FollowUpDrafts } from './FollowUpDrafts'
import { NegotiationDrafts, NegotiateButton } from './NegotiationDrafts'
import { RfqDrafts } from './RfqDrafts'
import { SupplierIntelligence } from './SupplierIntelligence'
import { Skeleton } from './ui'

const SOURCE_BADGE: Record<Doc<'suppliers'>['source'], string> = { firecrawl: 'bg-blue-950 text-blue-300 border-blue-900', demo: 'bg-emerald-950 text-emerald-300 border-emerald-900', manual: 'bg-neutral-800 text-neutral-300 border-neutral-700' }

export function SuppliersTab({ project }: { project: Doc<'projects'> }) {
  const suppliers = useQuery(api.suppliers.listSuppliers, { projectId: project._id })
  const matrix = useQuery(api.comparison.comparisonMatrix, { projectId: project._id })
  const config = useQuery(api.suppliers.getPublicConfig)
  const discoverSuppliers = useAction(api.discovery.discoverSuppliers)
  const researchSupplier = useAction(api.suppliers.researchSupplier)
  const mapSupplierWebsite = useAction(api.suppliers.mapSupplierWebsite)
  const crawlSupplierWebsite = useAction(api.suppliers.crawlSupplierWebsite)
  const refreshSupplierWebsite = useAction(api.suppliers.refreshSupplierWebsite)
  const setMonitoring = useMutation(api.suppliers.setSupplierMonitoring)
  const toggleSelected = useMutation(api.suppliers.toggleSupplierSelected)
  const setAutoApprove = useMutation(api.followups.setAutoApproveFollowUps)
  const [discovering, setDiscovering] = useState(false)
  const [researchingId, setResearchingId] = useState<Id<'suppliers'> | null>(null)
  const [actionBusy, setActionBusy] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [openNegotiationDraftId, setOpenNegotiationDraftId] = useState<Id<'drafts'> | null>(null)
  const [selectedSupplierId, setSelectedSupplierId] = useState<Id<'suppliers'> | null>(null)
  const selectedSupplier = suppliers?.find(s => s._id === selectedSupplierId) ?? null

  async function handleDiscover() { setError(null); setDiscovering(true); try { await discoverSuppliers({ projectId: project._id }) } catch (e) { setError(e instanceof Error ? e.message : 'Could not run supplier discovery.') } finally { setDiscovering(false) } }
  async function runSupplierAction(id: Id<'suppliers'>, key: string, fn: () => Promise<unknown>) { setError(null); setActionBusy(key); try { await fn() } catch (e) { setError(e instanceof Error ? e.message : 'Supplier action failed.') } finally { setActionBusy(null) } }
  const coverageBySupplier = new Map((matrix?.columns ?? []).map(column => [column.supplierId, column]))

  return <div className="space-y-4">
    <div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-medium text-neutral-300">Suppliers {suppliers ? `(${suppliers.length})` : ''}</h3><p className="mt-0.5 text-xs text-neutral-600">Discover, verify and monitor supplier evidence before sending an RFQ.</p>{config?.demoMode && <p className="text-xs text-amber-500 mt-0.5">Demo mode: only demo suppliers can be selected for an RFQ.</p>}</div><button onClick={() => void handleDiscover()} disabled={discovering || project.status === 'awarded'} title={project.status === 'awarded' ? 'Supplier discovery is disabled after award' : undefined} className="rounded-md bg-neutral-100 text-neutral-900 px-3 py-1.5 text-sm font-medium disabled:opacity-40 disabled:cursor-not-allowed">{discovering ? 'Discovering…' : project.status === 'awarded' ? 'Discovery closed' : 'Discover suppliers'}</button></div>
    {error && <p className="rounded-md border border-red-900/40 bg-red-950/20 px-3 py-2 text-sm text-red-300">{error}</p>}
    <label className="flex items-center gap-2 text-xs text-neutral-400 cursor-pointer w-fit"><input type="checkbox" checked={project.autoApproveFollowUps ?? false} onChange={e => void setAutoApprove({ projectId: project._id, enabled: e.currentTarget.checked })} />Auto-approve follow-up nudges to non-responding suppliers</label>
    {suppliers === undefined ? <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3"><Skeleton className="h-56"/><Skeleton className="h-56"/><Skeleton className="h-56"/></div> : suppliers.length === 0 ? <div className="rounded-lg border border-neutral-800 p-6 text-center"><p className="text-sm text-neutral-400">No suppliers yet. Generate a materials list first, then discover suppliers by category.</p></div> : <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{suppliers.map(s => {
      const locked = config?.demoMode === true && s.source !== 'demo'; const negotiationDisabled = project.status === 'awarded'; const intelligence = coverageBySupplier.get(s._id); const researchStatus = s.researchStatus ?? 'idle'
      return <div key={s._id} className="rounded-xl border border-neutral-800 p-4 space-y-3 text-left hover:border-neutral-600 hover:bg-white/[.015] transition">
        <button type="button" onClick={() => setSelectedSupplierId(s._id)} className="w-full text-left"><div className="flex items-start justify-between gap-2"><span className="font-medium text-sm text-neutral-100">{s.name}</span><span className={`shrink-0 rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wide ${SOURCE_BADGE[s.source]}`}>{s.source}</span></div><p className="mt-1 text-xs text-neutral-500 truncate">{s.email ?? 'N/A'}</p><div className="mt-2 flex flex-wrap gap-1">{s.categories.slice(0, 5).map(c => <span key={c} className="rounded bg-neutral-900 border border-neutral-800 px-1.5 py-0.5 text-[10px] text-neutral-400">{c}</span>)}</div></button>
        <div className="rounded-lg border border-white/[.06] bg-black/10 p-3"><div className="flex items-center justify-between gap-2"><span className="text-[10px] uppercase tracking-[.14em] text-neutral-600">Supplier research</span><span className="text-[10px] text-neutral-500">{researchStatus.replace('_', ' ')}</span></div>{s.researchedAt && <p className="mt-1 text-[11px] text-neutral-600">Last researched {new Date(s.researchedAt).toLocaleString()}</p>}{s.researchLocation && <p className="mt-1 text-[11px] text-neutral-500">{s.researchLocationVerified ? '✓' : '⚠'} {s.researchLocation}</p>}{s.researchEvidence?.[0] && <p className="mt-2 text-xs leading-5 text-neutral-400 line-clamp-2">{s.researchEvidence[0]}</p>}<div className="mt-2 flex flex-wrap gap-2"><button type="button" disabled={researchingId === s._id} onClick={() => { setResearchingId(s._id); void runSupplierAction(s._id, `research-${s._id}`, () => researchSupplier({ supplierId: s._id })).finally(() => setResearchingId(null)) }} className="bidwire-button bidwire-button-secondary text-xs">{researchingId === s._id ? 'Researching…' : 'Research supplier'}</button>{s.researchStatus === 'verified' && <span className="rounded-full border border-emerald-500/20 bg-emerald-500/[.06] px-2 py-1 text-[10px] text-emerald-300">Verified evidence</span>}</div></div>
        {intelligence && <div className="grid grid-cols-3 gap-2 border-t border-neutral-900 pt-3"><div><p className="text-[10px] uppercase tracking-wide text-neutral-700">Coverage</p><p className="mt-1 text-xs font-medium text-neutral-300">{intelligence.coveragePercent}%</p></div><div><p className="text-[10px] uppercase tracking-wide text-neutral-700">Version</p><p className="mt-1 text-xs font-medium text-neutral-300">v{intelligence.quoteVersion}</p></div><div><p className="text-[10px] uppercase tracking-wide text-neutral-700">Missing</p><p className="mt-1 text-xs font-medium text-neutral-300">{intelligence.missingLineItemIds.length}</p></div></div>}
        {s.status === 'replied' && <div className="flex items-center gap-2"><NegotiateButton projectId={project._id} supplierId={s._id} disabled={negotiationDisabled} onDraftReady={setOpenNegotiationDraftId}/>{negotiationDisabled && <span className="text-[10px] text-neutral-600">Awarded</span>}</div>}
        <div className="flex flex-wrap gap-2"><button type="button" disabled={!s.website || actionBusy !== null} onClick={() => void runSupplierAction(s._id, `map-${s._id}`, () => mapSupplierWebsite({ supplierId: s._id }))} className="bidwire-button bidwire-button-ghost text-[11px] disabled:opacity-40">{actionBusy === `map-${s._id}` ? 'Mapping…' : 'Map site'}</button><button type="button" disabled={!s.website || actionBusy !== null} onClick={() => void runSupplierAction(s._id, `crawl-${s._id}`, () => crawlSupplierWebsite({ supplierId: s._id }))} className="bidwire-button bidwire-button-ghost text-[11px] disabled:opacity-40">{actionBusy === `crawl-${s._id}` ? 'Crawling…' : 'Crawl site'}</button><button type="button" disabled={!s.website || actionBusy !== null} onClick={() => void runSupplierAction(s._id, `refresh-${s._id}`, () => refreshSupplierWebsite({ supplierId: s._id }))} className="bidwire-button bidwire-button-ghost text-[11px] disabled:opacity-40">{actionBusy === `refresh-${s._id}` ? 'Refreshing…' : 'Refresh web data'}</button></div>
        <label className={`flex items-center gap-2 pt-1 text-xs ${locked || project.status === 'awarded' ? 'text-neutral-600' : 'text-neutral-300 cursor-pointer'}`}><input type="checkbox" checked={s.status === 'selected'} disabled={locked || project.status === 'awarded'} onChange={() => void toggleSelected({ supplierId: s._id })} className="disabled:cursor-not-allowed" />Select for RFQ</label>
      </div>
    })}</div>}
    <SupplierIntelligence project={project} />
    <RfqDrafts project={project} /><FollowUpDrafts project={project} /><NegotiationDrafts project={project} openDraftId={openNegotiationDraftId} onClose={() => setOpenNegotiationDraftId(null)} />
    {selectedSupplier && <SupplierResearchModal supplier={selectedSupplier} onClose={() => setSelectedSupplierId(null)} onResearch={() => { setResearchingId(selectedSupplier._id); void runSupplierAction(selectedSupplier._id, `research-${selectedSupplier._id}`, () => researchSupplier({ supplierId: selectedSupplier._id })).finally(() => setResearchingId(null)) }} onMonitoring={enabled => void runSupplierAction(selectedSupplier._id, `monitor-${selectedSupplier._id}`, () => setMonitoring({ supplierId: selectedSupplier._id, enabled }))} />}
  </div>
}

function SupplierResearchModal({ supplier, onClose, onResearch, onMonitoring }: { supplier: Doc<'suppliers'>; onClose: () => void; onResearch: () => void; onMonitoring: (enabled: boolean) => void }) {
  return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" role="presentation" onMouseDown={onClose}><div className="w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-2xl border border-white/10 bg-[#0b0e0c] p-6 shadow-2xl" role="dialog" aria-modal="true" onMouseDown={e => e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.16em] text-neutral-600">Supplier intelligence profile</p><h2 className="mt-2 text-2xl font-semibold text-neutral-100">{supplier.name}</h2><p className="mt-1 text-sm text-neutral-500">{supplier.status} · {supplier.source} · {supplier.email ?? 'N/A'}</p></div><button onClick={onClose} className="text-neutral-500 hover:text-white text-xl" aria-label="Close supplier details">×</button></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-neutral-600">Location</p><p className="mt-1 text-sm text-neutral-200">{supplier.researchLocation ?? 'Not researched'}</p><p className="mt-1 text-xs text-neutral-500">{supplier.researchLocationVerified ? '✓ Verified against project location' : 'Needs verification'}</p></div><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-neutral-600">Contact</p><p className="mt-1 text-sm text-neutral-200 break-all">{supplier.email ?? 'N/A'}</p><p className="mt-1 text-xs text-neutral-500">{supplier.phone ?? 'Phone N/A'}</p></div><div className="rounded-xl border border-white/10 p-4"><p className="text-xs text-neutral-600">Research</p><p className="mt-1 text-sm text-neutral-200">{supplier.researchStatus ?? 'Not researched'}</p><p className="mt-1 text-xs text-neutral-500">{supplier.researchSourceCount ?? 0} source{(supplier.researchSourceCount ?? 0) === 1 ? '' : 's'} analyzed</p></div></div>
    {supplier.researchEvidence?.length ? <section className="mt-5"><h3 className="text-sm font-semibold">Why BidWire selected this supplier</h3><ul className="mt-2 space-y-2">{supplier.researchEvidence.map((x, i) => <li key={`${x}-${i}`} className="rounded-lg border border-white/[.06] bg-white/[.02] px-3 py-2 text-sm leading-5 text-neutral-400">{x}</li>)}</ul></section> : <p className="mt-5 text-sm text-neutral-500">No research evidence yet. Run supplier research to verify location, category relevance and public contact information.</p>}
    {supplier.researchReasons?.length ? <section className="mt-5"><h3 className="text-sm font-semibold">Match reasons</h3><div className="mt-2 flex flex-wrap gap-2">{supplier.researchReasons.map(x => <span key={x} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-neutral-300">{x}</span>)}</div></section> : null}
    <section className="mt-5"><h3 className="text-sm font-semibold">Relevant categories</h3><div className="mt-2 flex flex-wrap gap-2">{(supplier.researchCategories ?? supplier.categories).map(x => <span key={x} className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-xs text-neutral-300">{x}</span>)}</div></section>
    <section className="mt-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Public sources</h3><span className="text-xs text-neutral-600">Evidence, not endorsement</span></div>{supplier.researchSources?.length ? <div className="mt-2 divide-y divide-white/[.05] rounded-xl border border-white/10">{supplier.researchSources.map((source, i) => <a key={`${source.url}-${i}`} href={source.url} target="_blank" rel="noreferrer" className="block px-4 py-3 hover:bg-white/[.025]"><p className="truncate text-sm text-neutral-300">{source.title ?? source.url}</p><p className="mt-1 truncate text-xs text-neutral-600">{source.url}</p>{source.reason && <p className="mt-1 text-xs text-neutral-500">{source.reason}</p>}</a>)}</div> : <p className="mt-2 text-sm text-neutral-600">No public sources captured yet.</p>}</section>
    {supplier.listPrices?.length ? <section className="mt-5"><h3 className="text-sm font-semibold">Published prices</h3><div className="mt-2 divide-y divide-white/[.05] rounded-xl border border-white/10">{supplier.listPrices.map((p, i) => <div key={`${p.itemHint}-${i}`} className="flex items-center justify-between gap-4 px-4 py-3 text-sm"><span className="text-neutral-300">{p.itemHint}</span><span className="text-neutral-500">{p.price.toLocaleString()} / {p.unit}</span></div>)}</div></section> : null}
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-white/[.06] pt-5"><label className="flex items-center gap-2 text-xs text-neutral-400"><input type="checkbox" checked={supplier.monitoringEnabled ?? false} onChange={e => onMonitoring(e.currentTarget.checked)} disabled={!supplier.website} />Monitor supplier website for published-price changes</label><div className="flex gap-2"><button onClick={onResearch} className="bidwire-button bidwire-button-secondary">Research again</button><button onClick={onClose} className="bidwire-button bidwire-button-primary">Done</button></div></div>
  </div></div>
}
