import { Component, createContext, useContext, useEffect, useMemo, useState, type ErrorInfo, type ReactNode } from 'react'

type ToastKind='success'|'error'|'info';type ToastItem={id:number;kind:ToastKind;title:string;message?:string};type ToastContextValue={toast:(kind:ToastKind,title:string,message?:string)=>void};const ToastContext=createContext<ToastContextValue|null>(null)
export function ToastProvider({children}:{children:ReactNode}){const[items,setItems]=useState<ToastItem[]>([]);const api=useMemo<ToastContextValue>(()=>({toast(kind,title,message){const id=Date.now()+Math.random();setItems(c=>[...c,{id,kind,title,message}].slice(-4));window.setTimeout(()=>setItems(c=>c.filter(x=>x.id!==id)),4200)}}),[]);return <ToastContext.Provider value={api}>{children}<div className="fixed right-4 top-4 z-[100] flex w-[min(380px,calc(100vw-2rem))] flex-col gap-2" aria-live="polite">{items.map(item=><div key={item.id} className={`bidwire-toast bidwire-toast-${item.kind}`} role={item.kind==='error'?'alert':'status'}><div className="flex items-start gap-3"><span className="bidwire-toast-icon" aria-hidden>{item.kind==='success'?'✓':item.kind==='error'?'!':'i'}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{item.title}</p>{item.message&&<p className="mt-0.5 text-xs text-neutral-400">{item.message}</p>}</div><button className="bidwire-toast-close" onClick={()=>setItems(c=>c.filter(x=>x.id!==item.id))} aria-label="Dismiss notification">×</button></div></div>)}</div></ToastContext.Provider>}
export function useToast(){const value=useContext(ToastContext);if(!value)throw new Error('useToast must be used inside ToastProvider');return value}
export function Skeleton({className=''}:{className?:string}){return <div aria-hidden className={`bidwire-skeleton ${className}`}/>}
export function PageSkeleton(){return <div className="min-h-screen bg-[#070908] text-neutral-100"><div className="border-b border-white/10 px-4 py-4 sm:px-6"><div className="mx-auto flex max-w-[1440px] items-center justify-between"><Skeleton className="h-7 w-28"/><Skeleton className="h-8 w-24"/></div></div><main className="mx-auto max-w-[1440px] space-y-6 px-4 py-8 sm:px-6"><Skeleton className="h-10 w-64"/><div className="grid gap-4 sm:grid-cols-3"><Skeleton className="h-28"/><Skeleton className="h-28"/><Skeleton className="h-28"/></div><Skeleton className="h-72 w-full"/></main></div>}
export function EmptyState({icon,title,description,action}:{icon:string;title:string;description:string;action?:ReactNode}){return <div className="bidwire-empty"><div className="bidwire-empty-icon" aria-hidden>{icon}</div><h3 className="text-base font-semibold text-neutral-100">{title}</h3><p className="mt-1 max-w-md text-sm leading-6 text-neutral-500">{description}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function StatusPill({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'amber'|'green'|'red'|'blue'}){return <span className={`bidwire-status bidwire-status-${tone}`}>{children}</span>}
export function ConfirmDialog({open,title,description,confirmLabel='Confirm',destructive=false,onCancel,onConfirm}:{open:boolean;title:string;description:string;confirmLabel?:string;destructive?:boolean;onCancel:()=>void;onConfirm:()=>void}){useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')onCancel()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[open,onCancel]);if(!open)return null;return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" role="presentation" onMouseDown={onCancel}><div className="bidwire-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-title" onMouseDown={e=>e.stopPropagation()}><div className="bidwire-dialog-icon">{destructive?'!':'?'}</div><h2 id="confirm-title" className="text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-neutral-400">{description}</p><div className="mt-6 flex justify-end gap-2"><button className="bidwire-button bidwire-button-secondary" onClick={onCancel}>Cancel</button><button className={`bidwire-button ${destructive?'bidwire-button-danger':'bidwire-button-primary'}`} onClick={onConfirm}>{confirmLabel}</button></div></div></div>}
export class AppErrorBoundary extends Component<{children:ReactNode},{hasError:boolean}> {state={hasError:false};static getDerivedStateFromError(){return {hasError:true}}componentDidCatch(error:Error,info:ErrorInfo){console.error('BidWire render error',error,info)}render(){if(!this.state.hasError)return this.props.children;return <div className="min-h-screen bg-[#070908] px-4 py-16 text-neutral-100"><div className="mx-auto max-w-xl rounded-2xl border border-red-500/20 bg-red-950/10 p-6"><p className="text-xs uppercase tracking-[.16em] text-red-400">Something went wrong</p><h1 className="mt-2 text-xl font-semibold">This page could not be displayed.</h1><p className="mt-2 text-sm leading-6 text-neutral-400">Your data is still safe. Reload the page and continue from the project.</p><button className="bidwire-button bidwire-button-primary mt-5" onClick={()=>window.location.reload()}>Reload BidWire</button></div></div>}}
